### ISSUE TITLE
Does this work for deadops?

### ISSUE THREAD

**Issue by aepkolol** [JoakimCarlsson/ColdWarZombieTrainer#11]
Every time I lauch, it just crashes the app, running as admin.

**Comment by JoakimCarlsson** [comment]
Compile it as x64

**Comment by VerTox** [comment]
had same error, fixed by removing duplicate keys from weapon dictionary.

**Comment by JoakimCarlsson** [comment]
The issue with the weapon dictionary and duplicate keys is now fixed. Thanks.
