### ISSUE TITLE
Visual Studio Version

### ISSUE THREAD

**Issue by irize1000** [JoakimCarlsson/ColdWarZombieTrainer#18]
Hey mate,
thanks for the contribution !
which version of visual studio you used?
i tried to open the .sln file with 2019 and 2015 and it didnt opened

**Comment by irize1000** [comment]
add me on discord, please :)
iRiZe#0050

**Comment by 9zi** [comment]
> Hey mate,
> thanks for the contribution !
> which version of visual studio you used?
> i tried to open the .sln file with 2019 and 2015 and it didnt opened

try to open it with blend

**Comment by wakalol999** [comment]
hey, how do I compile the script?  I don't know how to use visual studio very well

**Comment by JoakimCarlsson** [comment]
Issue been solved via Discord.
