### ISSUE TITLE
Has Auto-Crits been fixed?

### ISSUE THREAD

**Issue by Vendorss** [JoakimCarlsson/ColdWarZombieTrainer#2]
Please allow us to ask here for when you will next update auto-criticals; This is a very interesting and hope inducing feature for the future of Aether unlocks.

**Comment by JoakimCarlsson** [comment]
That's a no, but I'll fix it later today and push and update.

**Comment by Vendorss** [comment]
Has Auto-Critical update been rolled into effect?

**Comment by JoakimCarlsson** [comment]
Yes, though I did it late at night. If might have forgotten too push synq :')

**Comment by Vendorss** [comment]
Just tested the newest build; can confirm the auto-criticals is not working.

**Comment by Vendorss** [comment]
Sir Meliodas#3217 hmu for a quicker form of contact.

**Comment by Vendorss** [comment]
Sir Meliodas#3217 hmu for a quicker form of contact.

**Comment by Vendorss** [comment]
Whats your discord
