### ISSUE TITLE
Update 1.8.2.8521522 offset changes

### ISSUE THREAD

**Issue by Coolmarve** [JoakimCarlsson/ColdWarZombieTrainer#21]
Update 1.8.2.8521522 offset changes, and now instaban on XP mods.

**Comment by WezXBL** [comment]
It builds, I open the trainer, Click Start, Trainer crashes.

I am clicking "Start" during the lobby screen which shouldnt make the trainer crash unless you have coded it to read certain offsets that require specific values to be considered ready to use.

Any help on fixing this?

**Comment by JoakimCarlsson** [comment]
If you updated all the offsets too the latest offsets.
Make sure you build it as a x64, And then run it as admin.
