### ISSUE TITLE
HOW???

### ISSUE THREAD

**Issue by Honey8Bunches** [JoakimCarlsson/ColdWarZombieTrainer#25]
How do i load this up on cod? or how do i pull up the menu in cod?

**Comment by dr-NHA** [comment]
this is not updated please learn 2 code

**Comment by dr-NHA** [comment]
https://www.se7ensins.com/members/honey-bunches.1608903/

**Comment by dr-NHA** [comment]
btw im sick of you kids calling mod tools menus XD
