### ISSUE TITLE
get an error when i try to open the .sln file.

### ISSUE THREAD

**Issue by commonono** [JoakimCarlsson/ColdWarZombieTrainer#3]
get an error when i try to open the .sln file.

also how do i make it undetected in the future myself? update the offsets or?

also could u add me on discord. 
rmc#0001

**Comment by Vendorss** [comment]
Making it undetected would involve adding Junk Code and a Polymorphic Engine to secure the File Hashes; MD5/SHA

**Comment by JoakimCarlsson** [comment]
Added.
