### ISSUE TITLE
Question. possible to put comments?

### ISSUE THREAD

**Issue by StevenGuilpin** [JoakimCarlsson/ColdWarZombieTrainer#4]
hello, i'm learning c # would it be possible to add comments to better understand the code? thank you

**Comment by JoakimCarlsson** [comment]
If you ask me the code is poorly written, so I would advice against learning from it. 

But, if you have any questions you can either email me. Or add me on discord is you have that.

**Comment by StevenGuilpin** [comment]
thank's

**Comment by Vendorss** [comment]
whats your discord

**Comment by JoakimCarlsson** [comment]
JCarlsson#1337
