### ISSUE TITLE
Gun Modifier Wrong Value

### ISSUE THREAD

**Issue by Andrew1175** [JoakimCarlsson/ColdWarZombieTrainer#8]
https://github.com/JoakimCarlsson/ColdWarZombieTrainer/blob/d63edec1adc91100dab70bee20505740e3878a8f/ColdWarZombieTrainer/MainWindow.xaml.cs#L208

This should be GunModiferSlider.Value

**Comment by JoakimCarlsson** [comment]
Oh, must have missed that.
Thanks a lot! Will fix as soon as I can.

**Comment by Andrew1175** [comment]
No problem man. I'm new to C# and actually took your code and recreated my own trainer with other features. (Purely for myself, I'm not posting it anywhere claiming your code is mine.) If you want to get together to work on this let me know. Right now I'm working on modifying your features to also affect other players in the lobby, not just yourself. I'm running into a snag though. :/

**Comment by JoakimCarlsson** [comment]
Add me on discord and I can help you.

DISCORD: Jcarlsson#1337

**Comment by Andrew1175** [comment]
I tried adding you and it's not finding you on Discord. Here's my Discord: TheWisestGuy#5170

**Comment by JoakimCarlsson** [comment]
Added.
